go_lang_image: &go_lang_image
  docker:
    - image: circleci/golang:1.14

slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0

work_directory: &work_directory
  working_directory: ~/slack-webhook-facade

resource_class: &resource_class
  resource_class: small

version: 2.1
jobs:
  test:
    <<: *go_lang_image
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go vet
  build:
    <<: *go_lang_image
    <<: *resource_class
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build -o docker/slackwebhookfacade main.go
      - save_cache:
          paths:
            - "/go/pkg"
          key: v1-pkg-cache
      - persist_to_workspace:
          root: ~/slack-webhook-facade
          paths:
            - docker/slackwebhookfacade
  deploy:
    executor: heroku/default
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - attach_workspace:
          at: ~/slack-webhook-facade
      - run: |
          TAG=0.1.0
          docker build -t devatherock/slack-webhook-facade:$TAG docker
          docker tag devatherock/slack-webhook-facade:$TAG devatherock/slack-webhook-facade:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/slack-webhook-facade:$TAG
          docker push devatherock/slack-webhook-facade:latest
          docker tag devatherock/slack-webhook-facade:$TAG registry.heroku.com/slack-webhook-facade/web
          heroku container:login
          docker push registry.heroku.com/slack-webhook-facade/web
          heroku container:release -a slack-webhook-facade web

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run: /bin/simpleslack -c "#33ad7f"
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack -c "#a1040c"
          when: on_fail

workflows:
  version: 2.1
  build_publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
      - notify_success:
          requires:
            - deploy
      - notify_failure:
          requires:
            - deploy
  pr_check:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
