slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.5.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

orbs:
  heroku: circleci/heroku@1.0.1

work_directory: &work_directory
  working_directory: ~/slack-webhook-facade

resource_class: &resource_class
  resource_class: small
  
executors:
  docker-executor:
    docker:
    - image: circleci/golang:1.14
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory    

version: 2.1
jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: make check
  build:
    executor: docker-executor
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: |
          make coveralls
          make build
      - save_cache:
          paths:
            - "/go/pkg"
          key: v1-pkg-cache
      - persist_to_workspace:
          root: ~/slack-webhook-facade
          paths:
            - docker/slackwebhookfacade
            
  publish:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/slack-webhook-facade
      - run: |
          TAG=${CIRCLE_SHA1:0:8}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t devatherock/slack-webhook-facade:$TAG docker
          docker push devatherock/slack-webhook-facade:$TAG
  deploy:
    executor: heroku/default
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - attach_workspace:
          at: ~/slack-webhook-facade
      - run: |
          TAG=${CIRCLE_TAG#v}
          DEV_TAG=${CIRCLE_SHA1:0:8}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull devatherock/slack-webhook-facade:$DEV_TAG
          docker tag devatherock/slack-webhook-facade:$DEV_TAG devatherock/slack-webhook-facade:$TAG
          docker tag devatherock/slack-webhook-facade:$TAG devatherock/slack-webhook-facade:latest
          docker push devatherock/slack-webhook-facade:$TAG
          docker push devatherock/slack-webhook-facade:latest
          docker tag devatherock/slack-webhook-facade:$TAG registry.heroku.com/slack-webhook-facade/web
          heroku container:login
          docker push registry.heroku.com/slack-webhook-facade/web
          heroku container:release -a slack-webhook-facade web

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack

workflows:
  version: 2.1
  build_publish:
    jobs:
      - build:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - publish:
          context:
            - docker-credentials
          requires:
            - build
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish
  release:
    jobs:
      - deploy:
          context:
            - docker-credentials
            - heroku-credentials
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - deploy
  pr_check:
    jobs:
      - test:
          context:
            - docker-credentials
          filters:
            branches:
              ignore: master
